# Generated by Django 5.2.8 on 2025-12-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='bank',
            field=models.CharField(default='SBI', max_length=32),
        ),
        migrations.AddField(
            model_name='statement',
            name='layout',
            field=models.CharField(default='SBI_POST_VALUE', max_length=64),
        ),
        migrations.AlterField(
            model_name='statement',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
